### ISSUE TITLE
 报错了

### ISSUE THREAD

**Issue by qq326646683** [mailgyc/doudizhu#1]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/Users/apple/Downloads/doudizhu-master/server/handler/web.py", line 53, in get
    self.render("auth_login.htm", error=None)
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/Library/Python/2.7/site-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/Library/Python/2.7/site-packages/tornado/template.py", line 454, in _create_template
    with open(path, "rb") as f:
IOError: [Errno 2] No such file or directory: '/Users/apple/Downloads/doudizhu-master/server/templates/auth_login.htm'
2017-06-14 00:44:37,536 - ERROR - 500 GET /auth/login?next=%2F (::1) 0.88ms

**Comment by mailgyc** [comment]
这个需要python3.6
